<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Resume Quote_ghost</name>
   <tag></tag>
   <elementGuidId>eda79d21-98b6-4330-9109-afcec6b279ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Resume Quote'])[1]/following::button[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ghost</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;clear-demo-state&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>156bc094-9b2a-47da-ab74-ad220a00f713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>clear-demo-state</value>
      <webElementGuid>0b3ae73d-1e19-4a5d-9cc4-997e646b7b8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ghost</value>
      <webElementGuid>579292d6-2fce-426a-8e8b-922ccbea4f72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mcp-ref</name>
      <type>Main</type>
      <value>e19</value>
      <webElementGuid>86f346c5-55bd-4c45-a4d3-187dffa60f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;shell&quot;]/div[@class=&quot;grid&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;inline&quot;]/button[@class=&quot;ghost&quot;]</value>
      <webElementGuid>fb0cf162-fb3b-4798-80c9-c7445463f219</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resume Quote'])[1]/following::button[1]</value>
      <webElementGuid>99c75d40-0c68-4f28-a317-fa8321c7e178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Quote'])[1]/following::button[2]</value>
      <webElementGuid>17751b47-4681-4cba-b4eb-fa46900f9ac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resume from: Start Quote'])[1]/preceding::button[1]</value>
      <webElementGuid>6e61d64a-597a-42f9-b9a7-49423012dd0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tip: Navigate via Start/Next/Back and the top nav links.'])[1]/preceding::button[1]</value>
      <webElementGuid>dde899dd-e603-4c31-a3f5-bde2d0835bcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Clear Demo State']/parent::*</value>
      <webElementGuid>284bb734-df3d-439f-93cf-ba7e53369a43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>f6f2de53-6915-416d-beb2-c4caf3677f3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
