<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2</name>
   <tag></tag>
   <elementGuidId>2b77a46f-d01b-41d6-81f1-40bb88db4afd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Tip: Navigate via Start/Next/Back and the top nav links.'])[1]/following::h2[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Execution Log (persisted)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>182fae58-2c7e-4594-a0e9-8fb10c43ccc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mcp-ref</name>
      <type>Main</type>
      <value>e23</value>
      <webElementGuid>81eeda68-3f8c-4e8d-b98e-5e257ac6c86f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;shell&quot;]/div[@class=&quot;grid&quot;]/div[@class=&quot;card&quot;]/h2[1]</value>
      <webElementGuid>b2e7d5fd-7e1c-4f97-8481-dd33909bbce9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tip: Navigate via Start/Next/Back and the top nav links.'])[1]/following::h2[1]</value>
      <webElementGuid>b6636596-f2a7-499b-b490-1188d4b61f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resume from: Start Quote'])[1]/following::h2[1]</value>
      <webElementGuid>e1d11485-b30d-42f0-bcbb-3dc5fbc3a88c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Execution Log (persisted)']/parent::*</value>
      <webElementGuid>d164b82e-cbfd-4528-a88f-e9d12c1466f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/h2</value>
      <webElementGuid>f6ae7737-f953-47f0-b23f-47fad6681014</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
